### ISSUE TITLE
Numerical stability

### ISSUE THREAD

**Issue by jan-glx** [const-ae/sparseMatrixStats#3]
Hi Consti, this package looks very promising!
I just needed support for sparse matrices in `matrixStats`!
While is is arguable not very relevant for most use cases of sparse matrices, numerical stability could be important for some. From looking at 
https://github.com/const-ae/sparseMatrixStats/blob/f4221ff8fd8b655151565443570e87cf8f2c6ce1/src/methods.cpp#L246
it seems like `sparseMatrixStats` might have some problems there...

See also:
https://en.wikipedia.org/wiki/Kahan_summation_algorithm
https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm

**Comment by const-ae** [comment]
Hi Jan, thanks for open the issue. 
You're right that I didn't put any effort into making sure that numerical stability is optimal at this early moment and also because I don't have much experience in this field.

Do I understand correctly that there are basically two issues right now: first, the numerical stability of the summing like this
```C++
double accum = 0.0;
double accum2 = 0.0;
R_len_t size = number_of_zeros;
std::for_each(values.begin(), values.end(),
              [&](auto d){
                ++size;
                accum += d;
                accum2 += pow(d, 2);
              });
```
and second that I can run into numerical issues by first summing up all the values and only in the end dividing by `n` instead of using an online algorithm?
The solution would be to implement Welford's algorithm, right?

**Comment by jan-glx** [comment]
I have never even touched a copy of Knuth: " The Art of Computer Programming", so I don't know. 
[matrixStats does two passes](https://github.com/HenrikBengtsson/matrixStats/blob/8bd3438c70955f84a761c4bc28cefa8188de6967/src/rowVars_lowlevel_template.h#L95-L101), so [does Armadillo (with a fallback to something else)
](https://gitlab.com/conradsnicta/armadillo-code/blob/9.800.x/include/armadillo_bits/op_var_meat.hpp#L166). For the sum, it depends a lot on what you are summing, most people don't care, I think, so I wouldn't either...

**Comment by const-ae** [comment]
I have implemented a more stable version for summing numbers by using a `long double` as accumulator (just like `base::sum()` and `matrixStats`). Secondly, I have switched the implementation for the variance to use 2 passes over the data, as you suggested.
